export const gameConstants = {
    CREATE_SUCCESS: 'GAME_CREATE_SUCCESS',
    CREATE_FAILURE: 'GAME_CREATE_FAILURE',

    GET_SUCCESS: 'GAME_GET_SUCCESS',
    GET_FAILURE: 'GAME_GET_FAILURE',

    JOIN_SUCCESS: 'GAME_JOIN_SUCCESS',
    JOIN_FAILURE: 'GAME_JOIN_FAILURE',

    START_SUCCESS: 'GAME_START_SUCCESS',
    START_FAILURE: 'GAME_START_FAILURE',

    CREATE_RANDOM_GAME_SUCCESS: 'GAME_CREATE_RANDOM_SUCCESS',

    GET_ACTIVE_SUCCESS: 'GAME_GET_ACTIVE_SUCCESS',
    GET_ACTIVE_FAILURE: 'GAME_GET_ACTIVE_FAILURE'
};