export const gameConstants = {
    CREATE_SUCCESS: 'GAME_CREATE_SUCCESS',
    CREATE_FAILURE: 'GAME_CREATE_FAILURE',

    GET_SUCCESS: 'GAME_GET_SUCCESS',
    GET_FAILURE: 'GAME_GET_FAILURE',

    START_SUCCESS: 'GAME_START_SUCCESS',
    START_FAILURE: 'GAME_START_FAILURE',

    GET_ALL_SUCCESS: 'GAME_GET_ALL_SUCCESS',
    GET_ALL_FAILURE: 'GAME_GET_ALL_FAILURE'
};