export const userConstants = {
    SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'USER_SIGNUP_FAILURE',

    LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

    GET_TOKEN_SUCCESS: 'USER_GET_TOKEN_SUCCESS',
    GET_TOKEN_FAILURE: 'USER_GET_TOKEN_FAILURE',

    LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'USER_LOGOUT_FAILURE',

    GET_SUCCESS: 'USER_GET_SUCCESS',
    GET_FAILURE: 'USER_GET_FAILURE'
};